### ISSUE TITLE
почистить репозиторий

### ISSUE THREAD

**Issue by Vaysman** [i-wanna-be-a-programmer/currency-converter#1]
Убрать директории и добавить их в `.gitignore`
* `.gradle`
* `.idea`
* `build`

**Comment by OldMan35** [comment]
done

**Comment by Vaysman** [comment]
> done

нет. вы сделали так, что теперь проект даже не соберется .

**Comment by OldMan35** [comment]
> > done
> 
> нет. вы сделали так, что теперь проект даже не соберется .

внес правки.
