### ISSUE TITLE
Классы принято называть с большой буквы и в CamelCase

### ISSUE THREAD

**Issue by Vaysman** [i-wanna-be-a-programmer/currency-converter#3]
https://github.com/i-wanna-be-a-programmer/currency-converter/blob/58f1f9a87c75f58bc62812b3c99f218649afd219/main/java/com/example/CurrencyConverter/controller.java#L9

https://github.com/i-wanna-be-a-programmer/currency-converter/blob/58f1f9a87c75f58bc62812b3c99f218649afd219/main/java/com/example/CurrencyConverter/currencyExchangeRate.java#L3

https://github.com/i-wanna-be-a-programmer/currency-converter/blob/58f1f9a87c75f58bc62812b3c99f218649afd219/main/java/com/example/CurrencyConverter/currencyValue.java#L3

https://github.com/i-wanna-be-a-programmer/currency-converter/blob/58f1f9a87c75f58bc62812b3c99f218649afd219/main/java/com/example/CurrencyConverter/parserJson.java#L11

**Comment by OldMan35** [comment]
Нужен Ваш совет. В main не актуальная версия проекта, в  master актуальная версия проекта. Возможно установить master как дефолтную ветку? А main удалить. 

Гуглил как это сделать, но похоже у меня нет admin прав.

**Comment by Vaysman** [comment]
@OldMan35 

> Нужен Ваш совет. В main не актуальная версия проекта, в master актуальная версия проекта. Возможно установить master как дефолтную ветку? А main удалить.
> 
> Гуглил как это сделать, но похоже у меня нет admin прав.

я поменял

**Comment by OldMan35** [comment]
Прошу посмотреть проект. Какие будут замечания?

**Comment by Vaysman** [comment]
> Прошу посмотреть проект. Какие будут замечания?

https://github.com/i-wanna-be-a-programmer/charter/blob/master/FAQ.md

**Comment by OldMan35** [comment]
> > Прошу посмотреть проект. Какие будут замечания?
> 
> https://github.com/i-wanna-be-a-programmer/charter/blob/master/FAQ.md

понял
